<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260403133646 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, original_name VARCHAR(255) NOT NULL, stored_name VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, extension VARCHAR(10) NOT NULL, size INT NOT NULL, file_path VARCHAR(500) NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, description TEXT DEFAULT NULL, subject_id INT DEFAULT NULL, exercise_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A7623EDC87 ON document (subject_id)');
        $this->addSql('CREATE INDEX IDX_D8698A76E934951A ON document (exercise_id)');
        $this->addSql('CREATE TABLE dql_subject (has_joins BOOLEAN NOT NULL, has_subqueries BOOLEAN NOT NULL, has_aggregations BOOLEAN NOT NULL, has_query_builder BOOLEAN NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A7623EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76E934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id)');
        $this->addSql('ALTER TABLE dql_subject ADD CONSTRAINT FK_C2F2C82EBF396750 FOREIGN KEY (id) REFERENCES subject (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A7623EDC87');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76E934951A');
        $this->addSql('ALTER TABLE dql_subject DROP CONSTRAINT FK_C2F2C82EBF396750');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE dql_subject');
    }
}
