<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260403154322 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exercise_attempt (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, answer TEXT NOT NULL, is_correct BOOLEAN DEFAULT NULL, attempted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notes TEXT DEFAULT NULL, question_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C2F9F5231E27F6BF ON exercise_attempt (question_id)');
        $this->addSql('ALTER TABLE exercise_attempt ADD CONSTRAINT FK_C2F9F5231E27F6BF FOREIGN KEY (question_id) REFERENCES exercise_question (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exercise_question ALTER hint DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exercise_attempt DROP CONSTRAINT FK_C2F9F5231E27F6BF');
        $this->addSql('DROP TABLE exercise_attempt');
        $this->addSql('ALTER TABLE exercise_question ALTER hint SET NOT NULL');
    }
}
