<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260403145508 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exercise_question (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, question_text TEXT NOT NULL, correction TEXT NOT NULL, hint TEXT NOT NULL, sort_order INT NOT NULL, exercise_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B09BE9A6E934951A ON exercise_question (exercise_id)');
        $this->addSql('ALTER TABLE exercise_question ADD CONSTRAINT FK_B09BE9A6E934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exercise_question DROP CONSTRAINT FK_B09BE9A6E934951A');
        $this->addSql('DROP TABLE exercise_question');
    }
}
