<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260403095711 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, instructions TEXT NOT NULL, difficulty INT NOT NULL, estimated_minutes INT NOT NULL, expected_output TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, subject_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AEDAD51C23EDC87 ON exercise (subject_id)');
        $this->addSql('CREATE TABLE php_subject (php_version VARCHAR(10) NOT NULL, has_oop BOOLEAN NOT NULL, has_functions BOOLEAN NOT NULL, has_file_handling BOOLEAN NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE postgresql_subject (pg_version VARCHAR(10) NOT NULL, has_jsonb BOOLEAN NOT NULL, has_transactions BOOLEAN NOT NULL, has_indexing BOOLEAN NOT NULL, has_window_functions BOOLEAN NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, sort_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, subject_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E3DE47723EDC87 ON skill (subject_id)');
        $this->addSql('CREATE TABLE skill_exercise (skill_id INT NOT NULL, exercise_id INT NOT NULL, PRIMARY KEY (skill_id, exercise_id))');
        $this->addSql('CREATE INDEX IDX_EC72B8EE5585C142 ON skill_exercise (skill_id)');
        $this->addSql('CREATE INDEX IDX_EC72B8EEE934951A ON skill_exercise (exercise_id)');
        $this->addSql('CREATE TABLE skill_validation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, validated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, mentor_note TEXT DEFAULT NULL, self_note TEXT DEFAULT NULL, skill_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_325871C5585C142 ON skill_validation (skill_id)');
        $this->addSql('CREATE TABLE subject (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE symfony_subject (symfony_version VARCHAR(10) NOT NULL, has_routing BOOLEAN NOT NULL, has_service BOOLEAN NOT NULL, has_form_builder BOOLEAN NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE exercise ADD CONSTRAINT FK_AEDAD51C23EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE php_subject ADD CONSTRAINT FK_4D926420BF396750 FOREIGN KEY (id) REFERENCES subject (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE postgresql_subject ADD CONSTRAINT FK_CC6BD84EBF396750 FOREIGN KEY (id) REFERENCES subject (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill ADD CONSTRAINT FK_5E3DE47723EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE skill_exercise ADD CONSTRAINT FK_EC72B8EE5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_exercise ADD CONSTRAINT FK_EC72B8EEE934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_validation ADD CONSTRAINT FK_325871C5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE symfony_subject ADD CONSTRAINT FK_B0DDAF22BF396750 FOREIGN KEY (id) REFERENCES subject (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exercise DROP CONSTRAINT FK_AEDAD51C23EDC87');
        $this->addSql('ALTER TABLE php_subject DROP CONSTRAINT FK_4D926420BF396750');
        $this->addSql('ALTER TABLE postgresql_subject DROP CONSTRAINT FK_CC6BD84EBF396750');
        $this->addSql('ALTER TABLE skill DROP CONSTRAINT FK_5E3DE47723EDC87');
        $this->addSql('ALTER TABLE skill_exercise DROP CONSTRAINT FK_EC72B8EE5585C142');
        $this->addSql('ALTER TABLE skill_exercise DROP CONSTRAINT FK_EC72B8EEE934951A');
        $this->addSql('ALTER TABLE skill_validation DROP CONSTRAINT FK_325871C5585C142');
        $this->addSql('ALTER TABLE symfony_subject DROP CONSTRAINT FK_B0DDAF22BF396750');
        $this->addSql('DROP TABLE exercise');
        $this->addSql('DROP TABLE php_subject');
        $this->addSql('DROP TABLE postgresql_subject');
        $this->addSql('DROP TABLE skill');
        $this->addSql('DROP TABLE skill_exercise');
        $this->addSql('DROP TABLE skill_validation');
        $this->addSql('DROP TABLE subject');
        $this->addSql('DROP TABLE symfony_subject');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
